In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas import ExcelWriter

#Read csv file
#I have chosen columns that will be independent variables in the eventual ML model. They cannot be averages, as they will be incorrect values when later pivoting the data
cols = ['Year', 'Player', 'Pos', 'Tm', 'G', 'MP', 'PER', '3PAr', 'FTr','OWS','DWS','WS','FG','FGA','3P','3PA','2P','2PA','FT','FTA','ORB','DRB','TRB','AST','STL','BLK','PF','PTS']
stats = pd.read_csv ('/content/Seasons_Stats.csv', usecols = cols)

#The way this data is formatted, there is a line of data for every team of every season that a player has ever played and another total ("TOT") line. For example, if you played on the Celtics and Lakers in the same season, there will be 3 lines of data. To avoid double coutning stats, I will filter out all total lines.
stats = stats[stats['Tm'] != "TOT"]

#stats = stats[stats['Year'] < 2015]
#stats = stats[stats['Year'] >1980]


stats

         Year             Player  Pos   Tm  ...   STL   BLK     PF    PTS
0      1950.0    Curly Armstrong  G-F  FTW  ...   NaN   NaN  217.0  458.0
1      1950.0       Cliff Barker   SG  INO  ...   NaN   NaN   99.0  279.0
2      1950.0      Leo Barnhorst   SF  CHS  ...   NaN   NaN  192.0  438.0
4      1950.0         Ed Bartels    F  DNN  ...   NaN   NaN   27.0   59.0
5      1950.0         Ed Bartels    F  NYK  ...   NaN   NaN    2.0    4.0
...       ...                ...  ...  ...  ...   ...   ...    ...    ...
24686  2017.0        Cody Zeller   PF  CHO  ...  62.0  58.0  189.0  639.0
24687  2017.0       Tyler Zeller    C  BOS  ...   7.0  21.0   61.0  178.0
24688  2017.0  Stephen Zimmerman    C  ORL  ...   2.0   5.0   17.0   23.0
24689  2017.0        Paul Zipser   SF  CHI  ...  15.0  16.0   78.0  240.0
24690  2017.0        Ivica Zubac    C  LAL  ...  14.0  33.0   66.0  284.0

[22568 rows x 28 columns]

In [ ]:
#stats = pd.pivot_table(data=stats,index=['Player'],aggfunc={'G':np.sum,'MP':np.sum })

#Create aggregrate dataview
#Most columns are aggregrated by sum, others such as PER and winshares are by mean
stats = pd.pivot_table(data=stats,index=['Player'],aggfunc={'Year':np.mean, 'G':np.sum, 'MP':np.sum, 'PER':np.mean, '3PAr':np.sum, 'FTr':np.sum,'OWS':np.mean,'DWS':np.mean,'WS':np.mean,'FG':np.sum,'FGA':np.sum,'3P':np.sum,'3PA':np.sum,'2P':np.sum,'2PA':np.sum,'FT':np.sum,'FTA':np.sum,'ORB':np.sum,'DRB':np.sum,'TRB':np.sum,'AST':np.sum,'STL':np.sum,'BLK':np.sum,'PF':np.sum,'PTS':np.sum})
stats

                        2P     2PA     3P  ...     TRB        WS         Year
Player                                     ...
A.C. Green          4420.0  8713.0  124.0  ...  9473.0  5.847059  1993.705882
A.J. Bramlett          4.0    21.0    0.0  ...    22.0 -0.200000  2000.000000
A.J. English         608.0  1353.0    9.0  ...   315.0  0.550000  1991.500000
A.J. Guyton           93.0   247.0   73.0  ...    80.0  0.100000  2002.000000
A.J. Hammons          12.0    32.0    5.0  ...    36.0  0.000000  2017.000000
...                    ...     ...    ...  ...     ...       ...          ...
Zelmo Beaty*        3396.0  7237.0    0.0  ...  5949.0  7.262500  1967.125000
Zendon Hamilton      176.0   400.0    0.0  ...   464.0  0.442857  2003.857143
Zoran Dragic           8.0    16.0    3.0  ...     8.0  0.000000  2015.000000
Zoran Planinic       160.0   358.0   37.0  ...   198.0  0.533333  2005.000000
Zydrunas Ilgauskas  4176.0  8742.0   31.0  ...  6191.0  5.107692  2004.846154

[3920 rows x 25 columns]

In [ ]:
#oldplayers = stats[stats['Year'] < 2009]
#oldplayers = oldplayers[oldplayers['Year'] >1980]
oldplayers

                         DWS       OWS        PER  ...       BPM       SPM       FPM
Player                                             ...
A.C. Green          2.417647  3.429412  13.958824  ...  0.014938  0.028261  0.066645
A.J. Bramlett       0.100000 -0.200000  -0.400000  ...  0.000000  0.016393  0.213115
A.J. English        0.700000 -0.200000  11.550000  ...  0.007722  0.018340  0.092342
A.J. Guyton        -0.033333  0.100000   4.366667  ...  0.009631  0.016051  0.046549
A.J. Wynder         0.000000 -0.100000   7.600000  ...  0.000000  0.025641  0.025641
...                      ...       ...        ...  ...       ...       ...       ...
Zarko Paspalj       0.200000 -0.500000   4.300000  ...  0.038674  0.016575  0.204420
Zeljko Rebraca      0.733333  0.633333  13.100000  ...  0.048780  0.017378  0.156098
Zendon Hamilton     0.200000  0.200000  12.800000  ...  0.017949  0.025000  0.137821
Zoran Planinic      0.700000 -0.200000   9.800000  ...  0.004419  0.036616  0.149621
Zydrunas Ilgauskas  2.515385  2.600000  17.769231  ...  0.057784  0.018332  0.120880

[1839 rows x 24 columns]

In [ ]:
#Create new calculated columns

#Percentages
stats["FG%"] = stats["FG"] / stats["FGA"] 
stats["FT%"] = stats["FT"] / stats["FTA"] 
stats["3P%"] = stats["3P"] / stats["3PA"] 
stats["eFG%"] = (stats["FG"] + 5 * stats["3P"] ) / stats["FGA"] 

#Per game averages
stats["PPG"] = stats["PTS"] / stats["G"] 
stats["APG"] = stats["AST"] / stats["G"] 
stats["RPG"] = stats["TRB"] / stats["G"] 
stats["ORPG"] = stats["ORB"] / stats["G"] 
stats["DRPG"] = stats["DRB"] / stats["G"] 
stats["BPG"] = stats["BLK"] / stats["G"] 
stats["SPG"] = stats["STL"] / stats["G"] 
stats["FPG"] = stats["PF"] / stats["G"] 

#Per game averages
stats["PPM"] = stats["PTS"] / stats["MP"] 
stats["APM"] = stats["AST"] / stats["MP"] 
stats["RPM"] = stats["TRB"] / stats["MP"] 
stats["ORPM"] = stats["ORB"] / stats["MP"] 
stats["DRPM"] = stats["DRB"] / stats["MP"] 
stats["BPM"] = stats["BLK"] / stats["MP"] 
stats["SPM"] = stats["STL"] / stats["MP"] 
stats["FPM"] = stats["PF"] / stats["MP"] 

stats

                        2P     2PA     3P  ...       BPM       SPM       FPM
Player                                     ...
A.C. Green          4420.0  8713.0  124.0  ...  0.014938  0.028261  0.066645
A.J. Bramlett          4.0    21.0    0.0  ...  0.000000  0.016393  0.213115
A.J. English         608.0  1353.0    9.0  ...  0.007722  0.018340  0.092342
A.J. Guyton           93.0   247.0   73.0  ...  0.009631  0.016051  0.046549
A.J. Hammons          12.0    32.0    5.0  ...  0.079755  0.006135  0.128834
...                    ...     ...    ...  ...       ...       ...       ...
Zelmo Beaty*        3396.0  7237.0    0.0  ...  0.001581  0.002453  0.116198
Zendon Hamilton      176.0   400.0    0.0  ...  0.017949  0.025000  0.137821
Zoran Dragic           8.0    16.0    3.0  ...  0.000000  0.026667  0.080000
Zoran Planinic       160.0   358.0   37.0  ...  0.004419  0.036616  0.149621
Zydrunas Ilgauskas  4176.0  8742.0   31.0  ...  0.057784  0.018332  0.120880

[3920 rows x 45 columns]

In [ ]:
list( stats.columns)

['2P',
 '2PA',
 '3P',
 '3PA',
 '3PAr',
 'AST',
 'BLK',
 'DRB',
 'DWS',
 'FG',
 'FGA',
 'FT',
 'FTA',
 'FTr',
 'G',
 'MP',
 'ORB',
 'OWS',
 'PER',
 'PF',
 'PTS',
 'STL',
 'TRB',
 'WS',
 'Year',
 'FG%',
 'FT%',
 '3P%',
 'eFG%',
 'PPG',
 'APG',
 'RPG',
 'ORPG',
 'DRPG',
 'BPG',
 'SPG',
 'FPG',
 'PPM',
 'APM',
 'RPM',
 'ORPM',
 'DRPM',
 'BPM',
 'SPM',
 'FPM']

In [ ]:
#Select columns that will be used in ML model
stats = stats.loc[:, ('DWS',
 'OWS',
 'PER',
 'WS',
 'FG%',
 'FT%',
 '3P%',
 'eFG%',
 'PPG',
 'APG',
 'RPG',
 'BPG',
 'SPG',
 'ORPG',
 'DRPG',
 'FPG',
 'PPM',
 'APM',
 'RPM',
 'ORPM',
 'DRPM',
 'BPM',
 'SPM',
 'FPM')]
stats

                         DWS       OWS        PER  ...       BPM       SPM       FPM
Player                                             ...
A.C. Green          2.417647  3.429412  13.958824  ...  0.014938  0.028261  0.066645
A.J. Bramlett       0.100000 -0.200000  -0.400000  ...  0.000000  0.016393  0.213115
A.J. English        0.700000 -0.200000  11.550000  ...  0.007722  0.018340  0.092342
A.J. Guyton        -0.033333  0.100000   4.366667  ...  0.009631  0.016051  0.046549
A.J. Hammons        0.200000 -0.200000   8.400000  ...  0.079755  0.006135  0.128834
...                      ...       ...        ...  ...       ...       ...       ...
Zelmo Beaty*        2.662500  4.612500  16.462500  ...  0.001581  0.002453  0.116198
Zendon Hamilton     0.200000  0.200000  12.800000  ...  0.017949  0.025000  0.137821
Zoran Dragic        0.000000 -0.050000   8.550000  ...  0.000000  0.026667  0.080000
Zoran Planinic      0.700000 -0.200000   9.800000  ...  0.004419  0.036616  0.149621
Zydrunas Ilgauskas  2.515385  2.600000  17.769231  ...  0.057784  0.018332  0.120880

[3920 rows x 24 columns]

In [ ]:
HoF = pd.read_csv ('/content/HoF.csv')
HoF = HoF.rename(columns={'Inductees':'Player'})
HoF

#import list of all star players
allstar = pd.read_csv ('/content/allstar.csv')
allstar

                  Player  Total  NBA  ABA
0    Kareem Abdul-Jabbar     19   19    0
1            Kobe Bryant     18   18    0
2          Julius Erving     16   11    5
3           LeBron James     16   16    0
4             Tim Duncan     15   15    0
..                   ...    ...  ...  ...
498          Mo Williams      1    1    0
499         Kevin Willis      1    1    0
500    Metta World Peace      1    1    0
501           Trae Young      1    1    0
502        Max Zaslofsky      1    1    0

[503 rows x 4 columns]

In [ ]:
df = pd.merge(stats,HoF,on='Player', how = 'inner', indicator = True)
df = pd.merge(stats,allstar,on='Player', how = 'left', indicator = True)
df
df['allstar'] = np.where(df['_merge']!= 'left_only', 1, 0)
df2 = df[df['allstar'] == 0]
df3 = df[df['allstar'] == 1]
#df3 = df2.sort_values('PER',ascending = False).groupby('Player').head(10)
#df2 = df2.set_index(['mainid','pidy']).groupby('pidx')['score'].nlargest(2).reset_index()
df2 = df2.nlargest(150, 'PER')

frames = [df2, df3]

result = pd.concat(frames)
result

                  Player       DWS       OWS  ...  ABA     _merge  allstar
3508         Steven Hill  0.000000  0.000000  ...  NaN  left_only        0
1616        Ian Lockhart  0.000000  0.000000  ...  NaN  left_only        0
3748       Tyson Wheeler  0.000000  0.100000  ...  NaN  left_only        0
918          Dave Scholz  0.000000  0.000000  ...  NaN  left_only        0
588       Chad Gallagher  0.000000  0.100000  ...  NaN  left_only        0
...                  ...       ...       ...  ...  ...        ...      ...
3878         Willie Wise  0.950000  0.300000  ...  3.0       both        1
3889   Woody Sauldsberry  1.771429 -2.914286  ...  0.0       both        1
3893     Xavier McDaniel  1.838462  1.838462  ...  0.0       both        1
3907       Zach Randolph  2.111765  2.570588  ...  0.0       both        1
3920  Zydrunas Ilgauskas  2.515385  2.600000  ...  0.0       both        1

[496 rows x 30 columns]

In [ ]:
#Select columns that will be used in ML model
dataset = result.loc[:, ('Player',
 'DWS',
 'OWS',
 'PER',
 'WS',
 'FG%',
 'FT%',
 '3P%',
 'eFG%',
 'PPG',
 'APG',
 'RPG',
 'BPG',
 'SPG',
 'ORPG',
 'DRPG',
 'FPG',
 'PPM',
 'APM',
 'RPM',
 'ORPM',
 'DRPM',
 'BPM',
 'SPM',
 'FPM',
 'allstar')]

dataset = dataset.replace([np.inf, -np.inf], np.nan)
dataset = dataset.fillna(0)
dataset

                  Player       DWS       OWS  ...       SPM       FPM  allstar
3508         Steven Hill  0.000000  0.000000  ...  0.000000  0.000000        0
1616        Ian Lockhart  0.000000  0.000000  ...  0.000000  0.000000        0
3748       Tyson Wheeler  0.000000  0.100000  ...  0.000000  0.333333        0
918          Dave Scholz  0.000000  0.000000  ...  0.000000  0.000000        0
588       Chad Gallagher  0.000000  0.100000  ...  0.000000  0.666667        0
...                  ...       ...       ...  ...       ...       ...      ...
3878         Willie Wise  0.950000  0.300000  ...  0.042463  0.128804        1
3889   Woody Sauldsberry  1.771429 -2.914286  ...  0.000000  0.112946        1
3893     Xavier McDaniel  1.838462  1.838462  ...  0.031388  0.101464        1
3907       Zach Randolph  2.111765  2.570588  ...  0.023922  0.075812        1
3920  Zydrunas Ilgauskas  2.515385  2.600000  ...  0.018332  0.120880        1

[496 rows x 26 columns]

In [ ]:
#DATA SCIENCE MACHINE LEARNING

X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
#Encoding the dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [ ]:
#Split dataset into Training and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = .2, random_state = 1)
X_train
np.any(np.isnan(X_train))
np.isfinite(X_test.all())

True

In [ ]:
#Feature scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Fit will get mean and SD, transform will apply mean and SD to the standardization formula


X_train [:,:] = sc.fit_transform(X_train [:,:])
X_test [:,:] = sc.transform(X_test [:,:])
X_train

array([[-0.89149008, -0.55555296, -0.59870683, ..., -0.37092124,
        -0.11473124, -0.09909207],
       [-1.3171019 , -1.04693417,  0.40888633, ...,  0.28768297,
        -0.52285189,  0.92452032],
       [-0.26348942, -0.99598829, -0.91214775, ..., -0.67023783,
        -0.97067612,  0.12974116],
       ...,
       [-0.63612299, -0.38178918, -0.4377454 , ..., -0.49422344,
         0.12399791, -0.27645084],
       [-0.05832269,  0.18792817, -0.43943529, ..., -0.50554766,
         0.53116796, -0.16541032],
       [-1.39448587, -1.11102737,  0.75108777, ..., -0.67772445,
        -1.0341123 , -1.464554  ]])

In [ ]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]]

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18  9]
 [ 5 68]]

0.86